server {
    listen 80;
    server_name blog.aadishds.live;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name blog.aadishds.live;

    ssl_certificate /etc/letsencrypt/live/blog.aadishds.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blog.aadishds.live/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location = /robots.txt {
        resolver 127.0.0.11 valid=30s;
        set $backend_url http://backend:3000;
        proxy_pass $backend_url;
        proxy_set_header Host $host;
    }

    location = /sitemap.xml {
        resolver 127.0.0.11 valid=30s;
        set $backend_url http://backend:3000;
        proxy_pass $backend_url;
        proxy_set_header Host $host;
    }

    location /api {
        resolver 127.0.0.11 valid=30s;
        set $backend_url http://backend:3000;
        proxy_pass $backend_url;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}